name: mini-blog

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mini-blog-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - mini-blog-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -C -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: mini-blog-sql-init
    networks:
    - mini-blog-net
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./docker/init.sql:/init.sql:ro
    entrypoint: >
      bash -c "
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong!Passw0rd' -i /init.sql
      "

volumes:
  sql_data:
networks:
  mini-blog-net:
    external: true